name: 🚀 Deploy MEDILINK

on:
  push:
    branches: ["develop"]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      # Variables de entorno (se toman de Secrets de GitHub)
      PORT: ${{ secrets.PORT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      MAILER_HOST: ${{ secrets.MAILER_HOST }}
      MAILER_EMAIL: ${{ secrets.MAILER_EMAIL }}
      MAILER_SECRET_KEY: ${{ secrets.MAILER_SECRET_KEY }}
      MAILER_SERVICE: ${{ secrets.MAILER_SERVICE }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      KEYCLOAK_JWKS_URI: ${{ secrets.KEYCLOAK_JWKS_URI }}

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar Node (usa la versión que definas en tu proyecto)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4️⃣ Compilar NestJS
      - name: Build backend
        run: npm run build

      # # 6️⃣ Reiniciar el servicio con PM2 o Docker (según tu entorno)
      # - name: Restart application
      #   run: |
      #     pm2 delete medilink || true
      #     pm2 start dist/main.js --name "medilink"

      # # 7️⃣ (Opcional) Verificar estado del servicio
      # - name: Verify deployment
      #   run: pm2 status medilink

